DROP TABLE IF EXISTS "share_cards" CASCADE;
DROP TABLE IF EXISTS "feature_flags" CASCADE;
DROP TABLE IF EXISTS "audit_logs" CASCADE;
DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "consents" CASCADE;
DROP TABLE IF EXISTS "safety_events" CASCADE;
DROP TABLE IF EXISTS "blocks" CASCADE;
DROP TABLE IF EXISTS "reports" CASCADE;
DROP TABLE IF EXISTS "ratings" CASCADE;
DROP TABLE IF EXISTS "meetup_messages" CASCADE;
DROP TABLE IF EXISTS "meetup_events" CASCADE;
DROP TABLE IF EXISTS "meetup_participants" CASCADE;
DROP TABLE IF EXISTS "meetups" CASCADE;
DROP TABLE IF EXISTS "service_zones" CASCADE;
DROP TABLE IF EXISTS "activity_types" CASCADE;
DROP TABLE IF EXISTS "interests" CASCADE;
DROP TABLE IF EXISTS "profiles" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP TYPE IF EXISTS "public"."report_category";
DROP TYPE IF EXISTS "public"."report_priority";
DROP TYPE IF EXISTS "public"."participant_status";
DROP TYPE IF EXISTS "public"."participant_role";
DROP TYPE IF EXISTS "public"."meetup_status";
DROP TYPE IF EXISTS "public"."moderation_status";
DROP TYPE IF EXISTS "public"."user_status";
DROP TYPE IF EXISTS "public"."user_role";
